const WIDTH = 800;
const HEIGHT = 400;
const MARGIN = { TOP: 20, BOTTOM: 50, LEFT: 50, RIGHT: 20 };
const INNER_WIDTH = WIDTH - MARGIN.LEFT - MARGIN.RIGHT;
const INNER_HEIGHT = HEIGHT - MARGIN.TOP - MARGIN.BOTTOM;

export { WIDTH, HEIGHT, MARGIN, INNER_WIDTH, INNER_HEIGHT };